/* tslint:disable */
/* eslint-disable */
//
// Representative TypeScript surface for @codonsplice/wasm.
// In the real build this file is GENERATED by wasm-bindgen (via wasm-pack) from
// the #[wasm_bindgen] annotations in crates/codonsplice-wasm/src/lib.rs. It is
// checked in here so editors get autocomplete before the first wasm build.

export default function init(
  module_or_path?: Request | URL | string | BufferSource | WebAssembly.Module,
): Promise<void>

/** A record returned from a query (variant, coverage window, alignment, …). */
export type CodonSpliceRecord = Record<string, unknown>

export class CodonSplice {
  /** Initialize the engine. Call once before anything else. */
  constructor()

  /** Compile a SpliceQL query and return disassembled bytecode. */
  compile(source: string): string

  /** Parse + type-check only. Returns null on success, an error string on failure. */
  check(source: string): string | null

  /**
   * Execute a query. `files` is `{ "name.bam": Uint8Array, ... }`; `vars` binds
   * `$variables` as `{ name: value }`. Returns an array of records/rows, or
   * `{ text: string }` for header/INTO queries.
   */
  execute(
    source: string,
    files: Record<string, Uint8Array>,
    vars: Record<string, string | number | boolean>,
  ): CodonSpliceRecord[] | { text: string }

  /** Execute pre-compiled `.spq.bc` bytecode against files + vars. */
  execute_bytecode(
    bytecode: Uint8Array,
    files: Record<string, Uint8Array>,
    vars: Record<string, string | number | boolean>,
  ): CodonSpliceRecord[] | { text: string }

  /** Stream results: onRecord per record, onDone at completion, onError on failure. */
  stream(
    source: string,
    files: Record<string, Uint8Array>,
    vars: Record<string, string | number | boolean>,
    onRecord: (record: CodonSpliceRecord) => void,
    onDone: () => void,
    onError: (error: unknown) => void,
  ): void

  /** The SpliceQL language version string. */
  static spliceql_version(): string

  /** The codonsplice-core engine version string. */
  static version(): string
}
